name: "🚀 release"

on:
  release:
    types: [published]

jobs:
  release:
    name: 🚀 release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.4.2
      - name: 🟢 node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org
      - name: 🚀 publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{publish.NPM_AUTH_TOKEN}}
